---
name: Approve pull requests
run-name: Approve pull requests (${{github.event.issue.number}})
on: issue_comment
jobs:
  approve:
    name: Approve a pull request (${{github.event.issue.number}})
    runs-on: ubuntu-24.04
    if: github.event.issue.pull_request && github.event.comment.body == '/approve'
    timeout-minutes: 10
    permissions:
      # Required to assume the AWS IAM role that signs the GitHub App JWT with KMS
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - uses: csm-actions/approve-pr-action@latest
        with:
          pull_request_number: ${{ github.event.issue.number }}
          app_id: ${{vars.AUTOFIX_TRIGGER_APP_ID}}
          aws_role_to_assume: ${{vars.AUTOFIX_TRIGGER_ROLE_TO_ASSUME}}
          aws_kms_key_id: ${{vars.AUTOFIX_TRIGGER_KMS_KEY_ID}}
          server_repository_name: securefix-demo-server
