---
name: securefix
# on: push
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: suzuki-shunsuke/pinact-action@pr/854
        with:
          securefix_app_id: ${{vars.AUTOFIX_TRIGGER_APP_ID}}
          securefix_app_private_key: ${{secrets.AUTOFIX_TRIGGER_APP_PRIVATE_KEY}}
          securefix_server_repository: securefix-demo-server
