---
name: securefix
# on: push
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: suzuki-shunsuke/update-pr-branch-action@latest
        with:
          max_behind_by: 0
          csm_app_id: ${{vars.AUTOFIX_TRIGGER_APP_ID}}
          csm_app_private_key: ${{secrets.AUTOFIX_TRIGGER_APP_PRIVATE_KEY}}
          csm_server: securefix-demo-server
          # files: |
          #   aqua/**
