---
name: Update pull request branch by pull request comment
on: issue_comment
jobs:
  update_branch:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      # Required to assume the AWS IAM role that signs the GitHub App JWT with KMS
      id-token: write
    if: github.event.issue.pull_request && contains(fromJSON('["/update-branch", "/ub"]'), github.event.comment.body)
    steps:
      - uses: csm-actions/update-branch-action@feat/oidc
        with:
          app_id: ${{vars.AUTOFIX_TRIGGER_APP_ID}}
          aws_role_to_assume: ${{vars.AUTOFIX_TRIGGER_ROLE_TO_ASSUME}}
          aws_kms_key_id: ${{vars.AUTOFIX_TRIGGER_KMS_KEY_ID}}
          server_repository_name: securefix-demo-server
